### ISSUE TITLE
PFSense Router Setup

### ISSUE THREAD

**Issue by SomethingGeneric** [SomethingGeneric/sparkle.local#1]
## Configure PFSense Firewall/Router Setup
--> Update with LAN IP Range + Default Gateway when available??

WAN IP: `10.0.17.102/24`

**Comment by SomethingGeneric** [comment]
![Image](https://github.com/SomethingGeneric/sparkle.local/assets/12242178/2e2b6c5b-0bc7-4816-8e8d-6080c947ebe9)

**Comment by SomethingGeneric** [comment]
LAN IP: `172.16.1.2`
No DHCP enabled right now.

**Comment by GitSyncPromedia** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
amalterawi, @hbarcelos, @0xAWM, @hantuzun, @CryptoPoolGit, @alenq1, @nvuillam, @lancenonce, @Crushedlex, @MSanchezWorld, @MRdoulestar, @lilpacy, @cs4storage, @bensadeghi, @dfoderick, @elektronaut0815, @yueduan, @OBIAGWUNNAMDI1, @tyler-cranmer, @doubledup, @Hackndo, @swieja, @Fors3cDream, @huaweigu, @Zo-L, @jamesmccomish, @maddyonline, @appsmonkey, @HyperJMX, @onura, @okanisis, @guozhe001, @zbaylin, @amazighe85, @fengzhi12, @Khushal-1234, @shaaaaawn, @poloplayingsolo, @luloxi, @atav32, @noyyyy, @arddluma, @KristianMika, @endziu, @notnian, @sekmet, @manolaz, @linxux, @JaCoderX, @AntonStrickland

**Comment by hupptechnologies** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
jalbiero, @xiyanxiyan11, @sudhir512kj, @songfj, @VincentNewkirk, @webenhanced, @s7v7nislands, @Kaperstone, @stevenling, @interbiznw, @xgithub, @liwenwei, @mahmadypour, @AceVVSWhite, @jooit, @littleserendipity, @zhangpeng-xjtu, @lapinpt, @Haoseo, @dk2nd, @DevrisOfStar, @Luvgordon, @wangxuemin, @aneopsy, @jackycute, @StellarRing, @lemonnight, @SenneDirkx, @bihuchao, @axboy, @nickbedner, @yangyuan6956873, @ZhouShuaiShuai, @eqieyiran, @naywin-programmer, @fdrgbs, @boudra, @richeshgupta, @williamd1k0, @AssoSwec, @sonoison, @naoki-yoshida97, @hawkmauk, @tangshd, @wanglav, @rrsc, @Hsankesara, @placecodex, @KamilJanda, @turpure

**Comment by anishmansuri** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
saranshkarira, @QiTai, @q578135872, @tangshanshan1998, @hawtim, @qinci, @CMCC-WY, @Start1090, @yinheze, @codex8089, @raymondware, @TE52, @robertchase05, @jerrycxj, @yinengy, @peterswa62, @megadeath, @SiberiaHLY, @DmitryBelenov, @piyush97, @newpote, @cuizhanming, @pavelkrolov, @shiva2492, @mkungla, @cMc-Enhancer, @cd365, @gooichi, @heathchyi, @Wangdi, @haigene, @lyoko98s, @mayank0403, @earthjeffone, @tututu-qiu, @nolledge, @Tuangit, @Georger0ot, @richartan, @ezeql, @rizkyaners, @proxyrunner, @jkintscher, @imwulv, @phainv, @leozvoy, @mrdede, @scott-ftf, @Vastyhao, @adriaanbd

**Comment by SDH-IT-HO** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
henryshi001, @Aver58, @falcononrails, @stormzy, @INASIC, @AmandaLocatelli, @Katastrophos, @PinkiVerma, @Jbeeze, @yaojun170, @cabrite11, @monuelo, @god-dog, @HereCMS, @RamyHakam, @dynchen, @PrincessEve, @adamclark64, @anzw, @LibmanBell, @little51, @Apathetictranscendentalist, @Drajeanne, @suganthyk, @Skykai521, @fr3fou, @takaxyz, @ancitmeong, @kaiwolfram, @Sharma-Hrishabh, @anoriqq, @nrkfeller, @waroi, @bigbigbo, @diguojin, @gaomc66, @wgtdkp, @Ahoo-Wang, @frennkie, @Akayeshmantha, @anchorhan, @Chufyjj, @hootio, @lindongobese, @ChadYanChuan, @wlfbitfc123, @ChanPoyu, @dubiaonfire, @MulderPu, @steven1227
